name: Share data 2

on: [workflow_dispatch, push]

jobs:

    download-job:
        name: Download output
        runs-on: ubuntu-latest
        steps:
        - name: Download a single artifact
          uses: actions/download-artifact@v4
          with:
            name: output-log-file
        - name: Print current dir
          run: pwd
        - name: List elements in current dir
          run: ls